# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from six import with_metaclass
from azure.core import CaseInsensitiveEnumMeta


class AuthorizationScopeFilter(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Defines what level of authorization resources should be returned based on the which
    subscriptions and management groups are passed as scopes.
    """

    AT_SCOPE_AND_BELOW = "AtScopeAndBelow"
    AT_SCOPE_AND_ABOVE = "AtScopeAndAbove"
    AT_SCOPE_EXACT = "AtScopeExact"
    AT_SCOPE_ABOVE_AND_BELOW = "AtScopeAboveAndBelow"

class ColumnDataType(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Data type of a column in a table.
    """

    STRING = "string"
    INTEGER = "integer"
    NUMBER = "number"
    BOOLEAN = "boolean"
    OBJECT = "object"
    DATETIME = "datetime"

class FacetSortOrder(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """The sorting order by the selected column (count by default).
    """

    ASC = "asc"
    DESC = "desc"

class ResultFormat(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Defines in which format query result returned.
    """

    TABLE = "table"
    OBJECT_ARRAY = "objectArray"

class ResultTruncated(with_metaclass(CaseInsensitiveEnumMeta, str, Enum)):
    """Indicates whether the query results are truncated.
    """

    TRUE = "true"
    FALSE = "false"
