# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AccountStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AccountStatus."""

    CREATING = "Creating"
    CREATED = "Created"
    UPDATING = "Updating"
    DELETING = "Deleting"
    FAILED = "Failed"


class CheckpointRetentionMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """CheckpointRetentionMode."""

    TTL = "Ttl"
    MAX_STORAGE = "MaxStorage"


class CompilationPolicyKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """CompilationPolicyKind."""

    JIT = "JIT"
    AOT = "AOT"


class ContainerImageKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ContainerImageKind."""

    PLATFORM = "Platform"
    CUSTOM = "Custom"


class IdleResourcesHandlingMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """IdleResourcesHandlingMode."""

    AUTO_SUSPEND = "AutoSuspend"
    AUTO_DELETE = "AutoDelete"


class InferenceMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """InferenceMode."""

    ONLINE = "Online"
    BATCH = "Batch"


class JobStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """JobStatus."""

    INITIALIZED = "Initialized"
    RUNNING = "Running"
    SUSPENDED = "Suspended"
    COMPLETED = "Completed"
    FAILED = "Failed"
    CANCELED = "Canceled"


class ModelStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ModelStatus."""

    CREATING = "Creating"
    READY = "Ready"
    DELETING = "Deleting"
    DEPLOYMENT_COMPLETED_WITH_ERROR = "DeploymentCompletedWithError"
    FAILED = "Failed"
    UPDATING = "Updating"


class MountOptionsKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """MountOptionsKind."""

    FUSE = "Fuse"
    INTERCEPTION = "Interception"


class NetworkKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """NetworkKind."""

    DELEGATED_SUBNET = "DelegatedSubnet"


class NetworkResourceStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """NetworkResourceStatus."""

    UNKNOWN = "Unknown"
    CREATING = "Creating"
    CREATED = "Created"
    DELETING = "Deleting"


class PolicyStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PolicyStatus."""

    CREATING = "Creating"
    CREATED = "Created"
    UPDATING = "Updating"
    DELETING = "Deleting"
    FAILED = "Failed"


class ProbeSettingKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ProbeSettingKind."""

    EXEC = "Exec"
    HTTP = "Http"


class ProtocolType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ProtocolType."""

    HTTPS = "Https"
    TCP = "Tcp"
    WEB_SOCKET = "WebSocket"
    SSH = "Ssh"


class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ProvisioningState."""

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CREATING = "Creating"
    UPDATING = "Updating"
    SUSPENDING = "Suspending"
    RESUMING = "Resuming"
    CANCELING = "Canceling"
    DELETING = "Deleting"


class SchedulingPriority(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """SchedulingPriority."""

    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class SlaTier(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """SlaTier."""

    PREMIUM = "Premium"
    STANDARD = "Standard"
    BASIC = "Basic"


class StorageAuthenticationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """StorageAuthenticationType."""

    NONE = "None"
    SAS_TOKEN = "SasToken"
    STORAGE_ACCOUNT_KEY = "StorageAccountKey"
    SYSTEM_ASSIGNED_IDENTITY = "SystemAssignedIdentity"
    USER_ASSIGNED_IDENTITY = "UserAssignedIdentity"


class StorageCacheKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """StorageCacheKind."""

    BLOB = "Blob"
    NFS = "NFS"
    ADLS = "ADLS"


class StorageCacheStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """StorageCacheStatus."""

    UNKNOWN = "Unknown"
    CREATING = "Creating"
    CREATED = "Created"
    DELETING = "Deleting"
    SUSPENDED = "Suspended"


class StorageSourceKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """StorageSourceKind."""

    AZURE_AI_SUPERCOMPUTER_STORAGE = "AzureAISupercomputerStorage"
    AZURE_BLOB_STORAGE = "AzureBlobStorage"
