#!/usr/bin/env bash

set - x
set - e
python3 -m venv ../venv-sdk
source ../venv-sdk/Scripts/activate
python scripts/dev_setup.py -p azure-core
python << EOF
print('[Generate]'+'$2')
with open('$2', 'w') as file_out:
  file_out.writelines(['{}\n'])
EOF