# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ActiveDirectory
    from ._models_py3 import AuthorizeRequest
    from ._models_py3 import AzureEntityResource
    from ._models_py3 import CapacityPool
    from ._models_py3 import CapacityPoolPatch
    from ._models_py3 import DailySchedule
    from ._models_py3 import Dimension
    from ._models_py3 import ExportPolicyRule
    from ._models_py3 import HourlySchedule
    from ._models_py3 import MetricSpecification
    from ._models_py3 import MonthlySchedule
    from ._models_py3 import MountTarget
    from ._models_py3 import MountTargetProperties
    from ._models_py3 import NetAppAccount
    from ._models_py3 import NetAppAccountPatch
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import ProxyResource
    from ._models_py3 import ReplicationObject
    from ._models_py3 import ReplicationStatus
    from ._models_py3 import Resource
    from ._models_py3 import ResourceNameAvailability
    from ._models_py3 import ResourceNameAvailabilityRequest
    from ._models_py3 import ServiceSpecification
    from ._models_py3 import Snapshot
    from ._models_py3 import SnapshotPolicy
    from ._models_py3 import SnapshotPolicyPatch
    from ._models_py3 import SnapshotPolicyVolumeList
    from ._models_py3 import TrackedResource
    from ._models_py3 import Volume
    from ._models_py3 import VolumePatch
    from ._models_py3 import VolumePatchPropertiesExportPolicy
    from ._models_py3 import VolumePropertiesDataProtection
    from ._models_py3 import VolumePropertiesExportPolicy
    from ._models_py3 import VolumeRevert
    from ._models_py3 import VolumeSnapshotProperties
    from ._models_py3 import WeeklySchedule
except (SyntaxError, ImportError):
    from ._models import ActiveDirectory
    from ._models import AuthorizeRequest
    from ._models import AzureEntityResource
    from ._models import CapacityPool
    from ._models import CapacityPoolPatch
    from ._models import DailySchedule
    from ._models import Dimension
    from ._models import ExportPolicyRule
    from ._models import HourlySchedule
    from ._models import MetricSpecification
    from ._models import MonthlySchedule
    from ._models import MountTarget
    from ._models import MountTargetProperties
    from ._models import NetAppAccount
    from ._models import NetAppAccountPatch
    from ._models import Operation
    from ._models import OperationDisplay
    from ._models import ProxyResource
    from ._models import ReplicationObject
    from ._models import ReplicationStatus
    from ._models import Resource
    from ._models import ResourceNameAvailability
    from ._models import ResourceNameAvailabilityRequest
    from ._models import ServiceSpecification
    from ._models import Snapshot
    from ._models import SnapshotPolicy
    from ._models import SnapshotPolicyPatch
    from ._models import SnapshotPolicyVolumeList
    from ._models import TrackedResource
    from ._models import Volume
    from ._models import VolumePatch
    from ._models import VolumePatchPropertiesExportPolicy
    from ._models import VolumePropertiesDataProtection
    from ._models import VolumePropertiesExportPolicy
    from ._models import VolumeRevert
    from ._models import VolumeSnapshotProperties
    from ._models import WeeklySchedule
from ._paged_models import CapacityPoolPaged
from ._paged_models import NetAppAccountPaged
from ._paged_models import OperationPaged
from ._paged_models import SnapshotPaged
from ._paged_models import SnapshotPolicyPaged
from ._paged_models import VolumePaged
from ._azure_net_app_files_management_client_enums import (
    InAvailabilityReasonType,
    CheckNameResourceTypes,
    ServiceLevel,
    EndpointType,
    ReplicationSchedule,
    RelationshipStatus,
    MirrorState,
)

__all__ = [
    'ActiveDirectory',
    'AuthorizeRequest',
    'AzureEntityResource',
    'CapacityPool',
    'CapacityPoolPatch',
    'DailySchedule',
    'Dimension',
    'ExportPolicyRule',
    'HourlySchedule',
    'MetricSpecification',
    'MonthlySchedule',
    'MountTarget',
    'MountTargetProperties',
    'NetAppAccount',
    'NetAppAccountPatch',
    'Operation',
    'OperationDisplay',
    'ProxyResource',
    'ReplicationObject',
    'ReplicationStatus',
    'Resource',
    'ResourceNameAvailability',
    'ResourceNameAvailabilityRequest',
    'ServiceSpecification',
    'Snapshot',
    'SnapshotPolicy',
    'SnapshotPolicyPatch',
    'SnapshotPolicyVolumeList',
    'TrackedResource',
    'Volume',
    'VolumePatch',
    'VolumePatchPropertiesExportPolicy',
    'VolumePropertiesDataProtection',
    'VolumePropertiesExportPolicy',
    'VolumeRevert',
    'VolumeSnapshotProperties',
    'WeeklySchedule',
    'OperationPaged',
    'NetAppAccountPaged',
    'CapacityPoolPaged',
    'VolumePaged',
    'SnapshotPaged',
    'SnapshotPolicyPaged',
    'InAvailabilityReasonType',
    'CheckNameResourceTypes',
    'ServiceLevel',
    'EndpointType',
    'ReplicationSchedule',
    'RelationshipStatus',
    'MirrorState',
]
