# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

class FeatureFlags(str, Enum):
    """FeatureFlags is the supported features of Azure SignalR service.
    
    
    * ServiceMode: Flag for backend server for SignalR service. Values allowed: "Default": have
    your own backend server; "Serverless": your application doesn't have a backend server;
    "Classic": for backward compatibility. Support both Default and Serverless mode but not
    recommended; "PredefinedOnly": for future use.
    * EnableConnectivityLogs: "true"/"false", to enable/disable the connectivity log category
    respectively.
    """

    service_mode = "ServiceMode"
    enable_connectivity_logs = "EnableConnectivityLogs"

class KeyType(str, Enum):
    """The keyType to regenerate. Must be either 'primary' or 'secondary'(case-insensitive).
    """

    primary = "Primary"
    secondary = "Secondary"

class ProvisioningState(str, Enum):
    """Provisioning state of the resource.
    """

    unknown = "Unknown"
    succeeded = "Succeeded"
    failed = "Failed"
    canceled = "Canceled"
    running = "Running"
    creating = "Creating"
    updating = "Updating"
    deleting = "Deleting"
    moving = "Moving"

class SignalRSkuTier(str, Enum):
    """Optional tier of this particular SKU. 'Standard' or 'Free'.
    
    ``Basic`` is deprecated, use ``Standard`` instead.
    """

    free = "Free"
    basic = "Basic"
    standard = "Standard"
    premium = "Premium"
