# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.paging import Paged


class ClusterPaged(Paged):
    """
    A paging container for iterating over a list of :class:`Cluster <azure.mgmt.streamanalytics.models.Cluster>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[Cluster]'}
    }

    def __init__(self, *args, **kwargs):

        super(ClusterPaged, self).__init__(*args, **kwargs)
class ClusterJobPaged(Paged):
    """
    A paging container for iterating over a list of :class:`ClusterJob <azure.mgmt.streamanalytics.models.ClusterJob>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[ClusterJob]'}
    }

    def __init__(self, *args, **kwargs):

        super(ClusterJobPaged, self).__init__(*args, **kwargs)
class PrivateEndpointPaged(Paged):
    """
    A paging container for iterating over a list of :class:`PrivateEndpoint <azure.mgmt.streamanalytics.models.PrivateEndpoint>` object
    """

    _attribute_map = {
        'next_link': {'key': 'nextLink', 'type': 'str'},
        'current_page': {'key': 'value', 'type': '[PrivateEndpoint]'}
    }

    def __init__(self, *args, **kwargs):

        super(PrivateEndpointPaged, self).__init__(*args, **kwargs)
