# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum, EnumMeta
from six import with_metaclass

class _CaseInsensitiveEnumMeta(EnumMeta):
    def __getitem__(self, name):
        return super().__getitem__(name.upper())

    def __getattr__(cls, name):
        """Return the enum member matching `name`
        We use __getattr__ instead of descriptors or inserting into the enum
        class' __dict__ in order to support `name` and `value` being both
        properties for enum members (which live in the class' __dict__) and
        enum members themselves.
        """
        try:
            return cls._member_map_[name.upper()]
        except KeyError:
            raise AttributeError(name)


class ClusterProvisioningState(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The status of the cluster provisioning. The three terminal states are: Succeeded, Failed and
    Canceled
    """

    SUCCEEDED = "Succeeded"  #: The cluster provisioning succeeded.
    FAILED = "Failed"  #: The cluster provisioning failed.
    CANCELED = "Canceled"  #: The cluster provisioning was canceled.
    IN_PROGRESS = "InProgress"  #: The cluster provisioning was inprogress.

class ClusterSkuName(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Specifies the SKU name of the cluster. Required on PUT (CreateOrUpdate) requests.
    """

    DEFAULT = "Default"  #: The default SKU.

class JobState(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The current execution state of the streaming job.
    """

    CREATED = "Created"  #: The job is currently in the Created state.
    STARTING = "Starting"  #: The job is currently in the Starting state.
    RUNNING = "Running"  #: The job is currently in the Running state.
    STOPPING = "Stopping"  #: The job is currently in the Stopping state.
    STOPPED = "Stopped"  #: The job is currently in the Stopped state.
    DELETING = "Deleting"  #: The job is currently in the Deleting state.
    FAILED = "Failed"  #: The job is currently in the Failed state.
    DEGRADED = "Degraded"  #: The job is currently in the Degraded state.
    RESTARTING = "Restarting"  #: The job is currently in the Restarting state.
    SCALING = "Scaling"  #: The job is currently in the Scaling state.
