# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, TYPE_CHECKING

from azure.core.rest import HttpRequest, HttpResponse
from azure.mgmt.core import ARMPipelineClient

from . import models
from ._configuration import BlockchainManagementClientConfiguration
from ._serialization import Deserializer, Serializer
from .operations import (
    BlockchainMemberOperationResultsOperations,
    BlockchainMembersOperations,
    LocationsOperations,
    Operations,
    SkusOperations,
    TransactionNodesOperations,
)

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials import TokenCredential


class BlockchainManagementClient:  # pylint: disable=client-accepts-api-version-keyword
    """REST API for Azure Blockchain Service.

    :ivar blockchain_members: BlockchainMembersOperations operations
    :vartype blockchain_members: azure.mgmt.blockchain.operations.BlockchainMembersOperations
    :ivar blockchain_member_operation_results: BlockchainMemberOperationResultsOperations
     operations
    :vartype blockchain_member_operation_results:
     azure.mgmt.blockchain.operations.BlockchainMemberOperationResultsOperations
    :ivar locations: LocationsOperations operations
    :vartype locations: azure.mgmt.blockchain.operations.LocationsOperations
    :ivar operations: Operations operations
    :vartype operations: azure.mgmt.blockchain.operations.Operations
    :ivar skus: SkusOperations operations
    :vartype skus: azure.mgmt.blockchain.operations.SkusOperations
    :ivar transaction_nodes: TransactionNodesOperations operations
    :vartype transaction_nodes: azure.mgmt.blockchain.operations.TransactionNodesOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: Gets the subscription Id which uniquely identifies the Microsoft Azure
     subscription. The subscription ID is part of the URI for every service call. Required.
    :type subscription_id: str
    :param base_url: Service URL. Default value is "https://management.azure.com".
    :type base_url: str
    :keyword api_version: Api Version. Default value is "2022-06-01". Note that overriding this
     default value may result in unsupported behavior.
    :paramtype api_version: str
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no
     Retry-After header is present.
    """

    def __init__(
        self,
        credential: "TokenCredential",
        subscription_id: str,
        base_url: str = "https://management.azure.com",
        **kwargs: Any
    ) -> None:
        self._config = BlockchainManagementClientConfiguration(
            credential=credential, subscription_id=subscription_id, **kwargs
        )
        self._client = ARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)
        self._serialize.client_side_validation = False
        self.blockchain_members = BlockchainMembersOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.blockchain_member_operation_results = BlockchainMemberOperationResultsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.locations = LocationsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.operations = Operations(self._client, self._config, self._serialize, self._deserialize)
        self.skus = SkusOperations(self._client, self._config, self._serialize, self._deserialize)
        self.transaction_nodes = TransactionNodesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )

    def _send_request(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client._send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> BlockchainManagementClient
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
